volumes:
  mysql:
  sandbox_mysql:

services:
  db:
    image: mysql:8.0
    container_name: sandbox_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - sandbox_mysql:/var/lib/mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  back:
    container_name: sandbox_back
    build:
      context: sandbox-nestjs
      dockerfile: Dockerfile
    environment:
      - TYPE=${TYPE}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - DATABASE=${DATABASE}
      - PORT=${PORT}
      - HOST=${HOST}
    volumes:
      - "./sandbox-nestjs:/app"
      - /app/node_modules
    restart: unless-stopped
    ports:
      - "3200:3000"
    depends_on:
      db:
        condition: service_healthy

  front:
    container_name: sandbox_front
    build:
      context: sandbox-nextjs
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
      - NODE_ENV=${NODE_ENV}
    volumes:
      - "./sandbox-nextjs:/app"
    restart: unless-stopped
    ports:
      - "3100:3000"
